### ISSUE TITLE
`irrefutPatError` with unsafe pattern matching in where clause

### ISSUE THREAD

**Issue by florentc** [BillHallahan/G2#81]
I have been running into some unexpected result with G2. I am not sure this is actually an issue or a subtlety I am not familiar with regarding non exhaustive pattern matching vs unsafe pattern matching in a where clause.

Consider the following functions:

```haskell
foo :: Int -> Int
foo x = y
  where
    Just y = if x > 0 then Nothing else Just x
```

and

```haskell
bar :: Int -> Int
bar x =
  case my of
    Just y -> y
  where
    my = if x > 0 then Nothing else Just x
```

There is a runtime execution when executing `foo` with G2 (`irrefutPatError` Irrefutable pattern failed for pattern)...
```
G2: evalVar: bad input.Id (Name "irrefutPatError" (Just "Control.Exception.Base") 3458764513820540937 Nothing) (TyForAll (NamedTyBndr (Id (Name "q" Nothing 3530822107858468881 Nothing) (TyCon (Name "RuntimeRep" (Just "GHC.Types") 3674937295934324926 Nothing) TYPE))) (TyForAll (NamedTyBndr (Id (Name "a" Nothing 3530822107858468865 Nothing) TYPE)) (TyFun (TyCon (Name "Addr#" (Just "GHC.Prim") 8214565720323796276 Nothing) TYPE) (TyVar (Id (Name "a" Nothing 3530822107858468865 Nothing) TYPE)))))
CallStack (from HasCallStack):
  error, called at src/G2/Execution/Rules.hs:124:19 in g2-0.1.0.1-inplace:G2.Execution.Rules
```

... whereas `bar` is executed normally and produces two branches including an `error` branch.
```
bar 0 = 0
bar 1 = error
```

**Comment by BillHallahan** [comment]
Thanks!  This is another case where there was an inadequacy in the base library, so you'll want to rerun base_setup.sh.  I added a test to G2 related to this issue, but if you don't care about that test you don't actually have to repull G2 at all.

For the `bar` function, GHC generates code which calls a function `patError` when the pattern match fails.  `patError` was included in our base library, so this worked correctly.  For the bar function, GHC generates code involving `irrefutPatError` which was _not_ in our base library, hence the error.  So the fix was simply adding `irrefutPatError` to the base library.
